### ISSUE TITLE
Sensors not working after upgrading to 2.0

### ISSUE THREAD

**Issue by jsk-sct** [Miicroo/ha-swedish_calendar#16]
Hi 
The sensors stopped working after I upgraded to 2.0. Did according to the new instructions and got this error:
```
Logger: homeassistant.components.sensor
Source: custom_components/swedish_calendar/types.py:15
Integration: Sensor (documentation, issues)
First occurred: 23:15:38 (1 occurrences)
Last logged: 23:15:38

Error while setting up swedish_calendar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/swedish_calendar/sensor.py", line 37, in async_setup_platform
    SwedishCalendarSensor(sensor_type, name, icon, state_key, default_value, attribution, coordinator))
  File "/config/custom_components/swedish_calendar/sensor.py", line 54, in __init__
    self._handle_coordinator_update()  # Set initial state
  File "/config/custom_components/swedish_calendar/sensor.py", line 97, in _handle_coordinator_update
    state = swedish_calendar.get_value_by_attribute(self.state_key)
  File "/config/custom_components/swedish_calendar/types.py", line 15, in get_value_by_attribute
    return self.themes.themes
AttributeError: 'NoneType' object has no attribute 'themes'
```
System is Hassio on Rpi4 and core is 2022.11.1
Hope this info helps cause I really like this integration for the workfree day sensor. It´s a much better sensor then 'weekend'.

/Johan

**Comment by Miicroo** [comment]
@jsk-sct Thank you for the report! It seems that there was a commit that I missed to push to the v2.0.0-branch that checked if themes were present or not, I have now added it and it seems to work. Tried without the change and got the same error as you did, so hoping this will resolve the issue.

**Comment by jsk-sct** [comment]
Sorry for late reply but downloaded the fix yesterday and now everything is working again

Good job and thank you again for the integration

/Johan

**Comment by Miicroo** [comment]
@jsk-sct Lovely to hear! Thanks for the bug report and glad that you like the integration!
